name: dymoval_dev

channels:
  - conda-forge
dependencies:
  # Runtime, must mirror [project].dependencies in pyproject.toml
  - matplotlib
  - scipy
  - control
  - numpy
  - h5py
  # Dev, must mirror [project.optional-dependencies].dev in pyproject.toml
  - sphinx
  - furo
  - sphinx-autodoc-typehints
  - pytest
  - mypy
  - ruff
  - coverage
  - grayskull
  - python-build
  - twine
  - pip
