name: dymoval_dev

channels:
  - conda-forge
dependencies:
  - pandas
  - matplotlib
  - mpl-measurements
  - control
  - scipy
  - pathlib
  - numpy
  - tomli
  - sphinx
  - furo
  - sphinx-autodoc-typehints
  - pytest
  - mypy
  - ruff
  - coverage
  - h5py
  - pip
