{% set name = "dymoval" %}
{% set version = "0.8.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dymoval-{{ version }}.tar.gz
  sha256: d590c5c1da55b08f0cbe69794bbe71e0bd107e5c7fd231fd5ba2862bd625f1cd

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.10
    - pdm-backend
    - pip
  run:
    - python >=3.10
    - pandas
    - matplotlib-base
    - scipy
    - control
    - pathlib
    - numpy
    - tomli
    - h5py

test:
  imports:
    - dymoval
  commands:
    - pip check
    - pytest .
  requires:
    - pip
    - pytest

about:
  home: https://github.com/ubaldot/dymoval
  summary: Dymoval is a Python package for validating models and analyzing datasets.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ubaldot
