{% set name = "dymoval" %}
{% set version = "0.8.83" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dymoval-{{ version }}.tar.gz
  sha256: 2d113f7a9a39c5e5d19f3fa5196fa230d93c9d702175c4b20ba917c17dd0e8e0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.10
    - pdm-backend
    - pip
  run:
    - python >=3.10
    - pandas
    - matplotlib-base
    - scipy
    - control
    - numpy
    - tomli
    - h5py

test:
  source_files:
    - src/
    - tests/
  imports:
    - dymoval
  commands:
    - pip check
    - pytest ./tests
  requires:
    - pip
    - pytest

about:
  home: https://github.com/ubaldot/dymoval
  summary: Dymoval is a Python package for validating models and analyzing datasets.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ubaldot
